# Generated by Django 5.1.3 on 2024-12-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptism',
            name='advanced_baptism_id',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
