# Generated by Django 5.1.3 on 2024-12-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0007_fieldtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtable',
            name='choice',
            field=models.CharField(choices=[('MULTIPLE', 'MULTIPLE'), ('MULTIPLE-SELECT', 'MULTIPLE-SELECT'), ('TEXT-AREA', 'TEXT-AREA')], default='MULTIPLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='fieldtable',
            name='type',
            field=models.CharField(choices=[('READING', 'READING'), ('SONG', 'SONG'), ('PRAYER', 'PRAYER'), ('REMARKS', 'REMARKS'), ('AUTHORIZATION', 'AUTHORIZATION'), ('FINANCIAL', 'FINANCIAL'), ('SPECIAL SAINTS', 'SPECIAL SAINTS')], default='READING', max_length=20),
        ),
    ]
