# Generated by Django 5.1.3 on 2024-12-04 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('basic_baptism_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('place_of_baptism', models.CharField(max_length=255)),
                ('date_of_baptism', models.DateField()),
                ('time_of_baptism', models.TimeField()),
                ('child_name_first', models.CharField(max_length=255)),
                ('child_name_second', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('mother_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('advanced_baptism_id', models.IntegerField()),
                ('priest_id', models.IntegerField()),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10)),
            ],
        ),
    ]
