# Generated by Django 5.1.3 on 2024-12-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0002_alter_baptism_advanced_baptism_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptism',
            name='advanced_baptism_id',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='priest_id',
            field=models.IntegerField(default=1),
        ),
    ]
