# Generated by Django 5.1.3 on 2024-12-07 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0003_alter_baptism_advanced_baptism_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParishDetails',
            fields=[
                ('parish_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_parish_id', models.IntegerField(default=1)),
                ('name_of_parish', models.CharField(max_length=255)),
                ('place_of_parish', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
