# Generated by Django 5.1.3 on 2024-12-12 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0004_parishdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaptismAdvanced',
            fields=[
                ('advanced_baptism_id', models.AutoField(primary_key=True, serialize=False)),
                ('basic_baptism_id', models.IntegerField()),
                ('q_id', models.IntegerField()),
                ('priest_id', models.IntegerField()),
                ('question', models.TextField()),
                ('question_type', models.CharField(max_length=255)),
                ('compulsary', models.BooleanField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('field_id', models.IntegerField()),
                ('data_varchar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('parish_id', models.IntegerField(default=1)),
            ],
        ),
    ]
