# Generated by Django 5.1.3 on 2024-12-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0009_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='basic_baptism_id',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='field_id',
            new_name='option_id',
        ),
    ]
