# Generated by Django 5.1.3 on 2024-12-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0010_rename_user_id_answer_basic_baptism_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='advanced_baptism_id',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
