# Generated by Django 5.1.3 on 2024-12-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0011_answer_advanced_baptism_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='advanced_baptism_id',
            field=models.IntegerField(default=1),
        ),
    ]
