# Generated by Django 5.1.3 on 2024-12-22 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0012_alter_answer_advanced_baptism_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('question_text', models.CharField(max_length=255)),
                ('answer_type', models.CharField(choices=[('radio', 'Radio'), ('text', 'Text')], max_length=10)),
                ('expand_question', models.TextField()),
                ('compulsary', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
