# Generated by Django 5.1.3 on 2024-12-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0014_alter_question_expand_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='expand_question',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
    ]
