# Generated by Django 5.1.3 on 2024-12-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0016_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('READING', 'READING'), ('SONG', 'SONG'), ('PRAYER', 'PRAYER'), ('REMARKS', 'REMARKS'), ('AUTHORIZATION', 'AUTHORIZATION'), ('FINANCIAL', 'FINANCIAL'), ('SPECIAL SAINTS', 'SPECIAL SAINTS')], default='READING', max_length=50),
        ),
        migrations.AlterField(
            model_name='answer',
            name='advanced_baptism_id',
            field=models.IntegerField(),
        ),
    ]
