# Generated by Django 5.1.3 on 2024-12-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0017_question_section_alter_answer_advanced_baptism_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('READING', 'READING'), ('SONG', 'SONG'), ('PRAYER', 'PRAYER'), ('REMARKS', 'REMARKS'), ('AUTHORIZATION', 'AUTHORIZATION'), ('FINANCIAL', 'FINANCIAL'), ('SPECIAL SAINTS', 'SPECIAL SAINTS')], max_length=50),
        ),
    ]
