# Generated by Django 5.1.3 on 2024-12-23 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0018_alter_question_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='baptism.question'),
        ),
    ]
