# Generated by Django 5.1.3 on 2024-12-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0022_alter_question_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('READING DETAILS', 'READING DETAILS'), ('THE PRAYER OF THE ASSEMBLY', 'THE PRAYER OF THE ASSEMBLY'), ('SONG SELECTION', 'SONG SELECTION'), ('REMARKS', 'REMARKS'), ('AUTHORIZATION', 'AUTHORIZATION'), ('FINANCIAL', 'FINANCIAL'), ('SPECIAL SAINTS', 'SPECIAL SAINTS')], max_length=50),
        ),
    ]
