# Generated by Django 5.1.3 on 2024-12-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0023_alter_question_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='type',
            field=models.CharField(choices=[('Radio', 'Radio'), ('Text', 'Text'), ('Checkbox', 'Checkbox')], default='Radio', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('radio', 'Radio'), ('text', 'Text'), ('checkbox', 'Checkbox')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('READING DETAILS', 'READING DETAILS'), ('THE PRAYER OF THE ASSEMBLY', 'THE PRAYER OF THE ASSEMBLY'), ('SPECIAL SAINTS TO COMMEMORATE', 'SPECIAL SAINTS TO COMMEMORATE'), ('SONG SELECTION', 'SONG SELECTION'), ('REMARKS', 'REMARKS'), ('AUTHORIZATION', 'AUTHORIZATION'), ('FINANCIAL PARTICIPATION', 'FINANCIAL PARTICIPATION')], max_length=50),
        ),
    ]
