# Generated by Django 5.1.3 on 2024-12-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0024_alter_option_type_alter_question_answer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baptism',
            name='godfather_name',
            field=models.CharField(default='Nil', max_length=255),
        ),
        migrations.AddField(
            model_name='baptism',
            name='godmother_name',
            field=models.CharField(default='Nil', max_length=255),
        ),
    ]
