# Generated by Django 5.1.3 on 2024-12-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0025_baptism_godfather_name_baptism_godmother_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptism',
            name='godfather_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='godmother_name',
            field=models.CharField(max_length=255),
        ),
    ]
