# Generated by Django 5.1.3 on 2024-12-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0026_alter_baptism_godfather_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='option_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
