# Generated by Django 5.1.3 on 2024-12-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0027_alter_answer_option_id_alter_answer_text_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deanery',
            fields=[
                ('deanery_id', models.AutoField(primary_key=True, serialize=False)),
                ('deanery_name', models.CharField(max_length=255)),
                ('dean_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='option_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
