# Generated by Django 5.1.3 on 2024-12-28 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0028_deanery_alter_answer_option_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishdetails',
            name='deanery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baptism.deanery'),
        ),
    ]
