# Generated by Django 5.1.3 on 2024-12-28 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0029_parishdetails_deanery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baptism.question'),
        ),
    ]
