# Generated by Django 5.1.3 on 2024-12-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0032_remove_parishdetails_parent_parish_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='baptism',
            name='remark',
            field=models.CharField(default='Nil', max_length=255),
        ),
    ]
