# Generated by Django 5.1.3 on 2024-12-28 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0034_baptism_parish_alter_baptism_place_of_baptism'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baptism',
            name='parish',
        ),
        migrations.AlterField(
            model_name='baptism',
            name='place_of_baptism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baptism.parishdetails'),
        ),
    ]
