# Generated by Django 5.1.3 on 2024-12-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0035_remove_baptism_parish_alter_baptism_place_of_baptism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptism',
            name='place_of_baptism',
            field=models.CharField(default='place1', max_length=255),
        ),
    ]
